services:
  postgres:
    image: postgres:16
    container_name: base44-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: nenos
      POSTGRES_PASSWORD: wJS9tXh9pQ9J4zAN
      POSTGRES_DB: oms_db
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
